embed_assets: on
gzip_assets: off

stylesheets:
  screen:
    - public/assets/src/n.css
    
javascripts:
  app:
    - public/js/jquery.equalHeights.js
    - public/assets/src/home.js
    - public/assets/src/app.js
    - public/assets/src/update.js
    - public/assets/src/updates.show.js
    - public/assets/src/users.js