embed_assets: on
gzip_assets: off
compress_assets: on

stylesheets:
  screen:
    - public/assets/src/n.css
    
javascripts:
  app:
    - public/js/lib/jquery.equalHeights.js
    - public/assets/src/main.js